name: Run Build Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      test_manifest: true
      manifest_ignored: "test/**,scripts/**,CHANGELOG.md"
  pip_audit:
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install skill
        run: |
          pip install .
      - uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          # Ignore setuptools vulnerability we can't do much about
          ignore-vulns: |
            GHSA-r9hx-vwmv-q579
